FROM openjdk:17-jdk-slim

WORKDIR /app
COPY . .

# Make mvnw executable
RUN chmod +x mvnw

# Build using wrapper
RUN ./mvnw clean package -DskipTests

CMD ["java", "-jar", "target/venuebooking-0.0.1-SNAPSHOT.jar"]
